### PR TITLE
Minor collectables improvements

### PR DESCRIPTION
**Pull request by lazyranma**
1) Option to use Solid Reason / Ageless Words when you are lucky enough to hit the target collectability rating with the filler rotation.
2) Always use Brazen if Collector's High Standard is up (this was true only for filler rotation).
3) Merge FillerRotation() and FullRotation() into one.

### CODE REVIEW

**Comment by C-Hat32** [comment]
Thanks for the improvements! 
My 2 cents on the rotations merge: the idea was to support multiple rotations for people with less stats/gp. Teamcraft guides currently feature 3 collectables rotations + the 0 gp rotation, I feel like merging the 0gp and the 1000gp rotations goes a bit against that logic, but I'll let @NostraThomas99 choose how he wants to handle that 😄

**Comment by lazyranma** [comment]
The base principle of both rotations is the same. The only difference was whether to use Scrutiny and Solid/Ageless or not. And after my first two commits, both functions became identical, safe for 2 lines related to Scrutiny and a flag check for Solid/Ageless, so it felt natural to merge them to reduce the amount of duplicate code.

**Comment by lazyranma** [comment]
As for Brazen changes, FullRotation() had a condition check to use it only if that would hit the target controllability score, which made it possible to use it only on the third step, while TeamCraft states that it should be used on the second step.

**Comment by lazyranma** [comment]
Are there any chances that this request gets approved?
Those changes are actually quite useful for gathering ephemeral nodes.

**Pull request merged**
